.class public final Lio/mironov/smuggler/AutoParcelable$DefaultImpls;
.super Ljava/lang/Object;
.source "AutoParcelable.kt"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lio/mironov/smuggler/AutoParcelable;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "DefaultImpls"
.end annotation

.annotation runtime Lkotlin/Metadata;
    bv = {
        0x1,
        0x0,
        0x2
    }
    k = 0x3
    mv = {
        0x1,
        0x1,
        0xa
    }
.end annotation


# direct methods
.method public static describeContents(Lio/mironov/smuggler/AutoParcelable;)I
    .locals 1

    .line 49
    new-instance p0, Ljava/lang/UnsupportedOperationException;

    const-string v0, "This method will never be used in runtime. The real implementation will be generated by smuggler plugin."

    invoke-direct {p0, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    check-cast p0, Ljava/lang/Throwable;

    throw p0
.end method

.method public static writeToParcel(Lio/mironov/smuggler/AutoParcelable;Landroid/os/Parcel;I)V
    .locals 0
    .param p1    # Landroid/os/Parcel;
        .annotation build Lorg/jetbrains/annotations/NotNull;
        .end annotation
    .end param

    const-string p0, "parcel"

    invoke-static {p1, p0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 45
    new-instance p0, Ljava/lang/UnsupportedOperationException;

    const-string p1, "This method will never be used in runtime. The real implementation will be generated by smuggler plugin."

    invoke-direct {p0, p1}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    check-cast p0, Ljava/lang/Throwable;

    throw p0
.end method
